/* Generated By:JJTree: Do not edit this line. ASTPommeDnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDnil::ASTPommeDnil(int id) : PommeNode(id) {
  }
  ASTPommeDnil::ASTPommeDnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDnil::~ASTPommeDnil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
