/* Generated By:JJTree: Do not edit this line. ASTPommeInput.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeInput.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeInput::ASTPommeInput(int id) : PommeNode(id) {
  }
  ASTPommeInput::ASTPommeInput(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeInput::~ASTPommeInput() {
  }

  /** Accept the visitor. **/
  void  ASTPommeInput::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
