/* Generated By:JJTree: Do not edit this line. ASTPommeOrEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeOrEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeOrEq::ASTPommeOrEq(int id) : PommeNode(id) {
  }
  ASTPommeOrEq::ASTPommeOrEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeOrEq::~ASTPommeOrEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeOrEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
