/* Generated By:JJTree: Do not edit this line. ASTPommeEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeEnum::ASTPommeEnum(int id) : PommeNode(id) {
  }
  ASTPommeEnum::ASTPommeEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeEnum::~ASTPommeEnum() {
  }

  /** Accept the visitor. **/
  void  ASTPommeEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
