/* Generated By:JJTree: Do not edit this line. ASTPommeCase.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeCase.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeCase::ASTPommeCase(int id) : PommeNode(id) {
  }
  ASTPommeCase::ASTPommeCase(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeCase::~ASTPommeCase() {
  }

  /** Accept the visitor. **/
  void  ASTPommeCase::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
