/* Generated By:JJTree: Do not edit this line. ASTPommePublic.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommePublic.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommePublic::ASTPommePublic(int id) : PommeNode(id) {
  }
  ASTPommePublic::ASTPommePublic(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommePublic::~ASTPommePublic() {
  }

  /** Accept the visitor. **/
  void  ASTPommePublic::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
