/* Generated By:JJTree: Do not edit this line. ASTPommeGlobalFunctionNative.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeGlobalFunctionNative.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeGlobalFunctionNative::ASTPommeGlobalFunctionNative(int id) : PommeNode(id) {
  }
  ASTPommeGlobalFunctionNative::ASTPommeGlobalFunctionNative(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeGlobalFunctionNative::~ASTPommeGlobalFunctionNative() {
  }

  /** Accept the visitor. **/
  void  ASTPommeGlobalFunctionNative::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
