/* Generated By:JJTree: Do not edit this line. ASTPommeGT.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeGT.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeGT::ASTPommeGT(int id) : PommeNode(id) {
  }
  ASTPommeGT::ASTPommeGT(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeGT::~ASTPommeGT() {
  }

  /** Accept the visitor. **/
  void  ASTPommeGT::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
