/* Generated By:JJTree: Do not edit this line. ASTPommeOmega.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeOmega.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeOmega::ASTPommeOmega(int id) : PommeNode(id) {
  }
  ASTPommeOmega::ASTPommeOmega(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeOmega::~ASTPommeOmega() {
  }

  /** Accept the visitor. **/
  void  ASTPommeOmega::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
