/* Generated By:JJTree: Do not edit this line. ASTPommeDecrPre.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDecrPre.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDecrPre::ASTPommeDecrPre(int id) : PommeNode(id) {
  }
  ASTPommeDecrPre::ASTPommeDecrPre(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDecrPre::~ASTPommeDecrPre() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDecrPre::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
