/* Generated By:JJTree: Do not edit this line. ASTPommeIdentOp.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeIdentOp.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeIdentOp::ASTPommeIdentOp(int id) : PommeNode(id) {
  }
  ASTPommeIdentOp::ASTPommeIdentOp(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeIdentOp::~ASTPommeIdentOp() {
  }

  /** Accept the visitor. **/
  void  ASTPommeIdentOp::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
