/* Generated By:JJTree: Do not edit this line. ASTPommeEnumDefault.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeEnumDefault.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeEnumDefault::ASTPommeEnumDefault(int id) : PommeNode(id) {
  }
  ASTPommeEnumDefault::ASTPommeEnumDefault(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeEnumDefault::~ASTPommeEnumDefault() {
  }

  /** Accept the visitor. **/
  void  ASTPommeEnumDefault::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
