/* Generated By:JJTree: Do not edit this line. ASTPommeScinil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeScinil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeScinil::ASTPommeScinil(int id) : PommeNode(id) {
  }
  ASTPommeScinil::ASTPommeScinil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeScinil::~ASTPommeScinil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeScinil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
