/* Generated By:JJTree: Do not edit this line. ASTPommeNull.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeNull.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeNull::ASTPommeNull(int id) : PommeNode(id) {
  }
  ASTPommeNull::ASTPommeNull(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeNull::~ASTPommeNull() {
  }

  /** Accept the visitor. **/
  void  ASTPommeNull::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
