/* Generated By:JJTree: Do not edit this line. ASTPommeDefault.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDefault.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDefault::ASTPommeDefault(int id) : PommeNode(id) {
  }
  ASTPommeDefault::ASTPommeDefault(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDefault::~ASTPommeDefault() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDefault::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
