/* Generated By:JJTree: Do not edit this line. ASTPommeTypeDef.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeTypeDef.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeTypeDef::ASTPommeTypeDef(int id) : PommeNode(id) {
  }
  ASTPommeTypeDef::ASTPommeTypeDef(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeTypeDef::~ASTPommeTypeDef() {
  }

  /** Accept the visitor. **/
  void  ASTPommeTypeDef::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
