/* Generated By:JJTree: Do not edit this line. ASTPommeReturn.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeReturn.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeReturn::ASTPommeReturn(int id) : PommeNode(id) {
  }
  ASTPommeReturn::ASTPommeReturn(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeReturn::~ASTPommeReturn() {
  }

  /** Accept the visitor. **/
  void  ASTPommeReturn::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
