/* Generated By:JJTree: Do not edit this line. ASTPommeOnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeOnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeOnil::ASTPommeOnil(int id) : PommeNode(id) {
  }
  ASTPommeOnil::ASTPommeOnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeOnil::~ASTPommeOnil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeOnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
