/* Generated By:JJTree: Do not edit this line. ASTPommeProtected.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeProtected.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeProtected::ASTPommeProtected(int id) : PommeNode(id) {
  }
  ASTPommeProtected::ASTPommeProtected(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeProtected::~ASTPommeProtected() {
  }

  /** Accept the visitor. **/
  void  ASTPommeProtected::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
