/* Generated By:JJTree: Do not edit this line. ASTPommeAcnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAcnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAcnil::ASTPommeAcnil(int id) : PommeNode(id) {
  }
  ASTPommeAcnil::ASTPommeAcnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAcnil::~ASTPommeAcnil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAcnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
