/* Generated By:JJTree: Do not edit this line. ASTPommeBreak.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeBreak.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeBreak::ASTPommeBreak(int id) : PommeNode(id) {
  }
  ASTPommeBreak::ASTPommeBreak(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeBreak::~ASTPommeBreak() {
  }

  /** Accept the visitor. **/
  void  ASTPommeBreak::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
