/* Generated By:JJTree: Do not edit this line. ASTPommeDecls.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDecls.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDecls::ASTPommeDecls(int id) : PommeNode(id) {
  }
  ASTPommeDecls::ASTPommeDecls(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDecls::~ASTPommeDecls() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDecls::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=7cb065a839150ff3ce3670b4c6755dec (do not edit this line) */
