/* Generated By:JJTree: Do not edit this line. ASTPommeCases.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeCases.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeCases::ASTPommeCases(int id) : PommeNode(id) {
  }
  ASTPommeCases::ASTPommeCases(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeCases::~ASTPommeCases() {
  }

  /** Accept the visitor. **/
  void  ASTPommeCases::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
