/* Generated By:JJTree: Do not edit this line. ASTPommeHeader.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeHeader.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeHeader::ASTPommeHeader(int id) : PommeNode(id) {
  }
  ASTPommeHeader::ASTPommeHeader(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeHeader::~ASTPommeHeader() {
  }

  /** Accept the visitor. **/
  void  ASTPommeHeader::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
