/* Generated By:JJTree: Do not edit this line. ASTPommeVoidType.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeVoidType.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeVoidType::ASTPommeVoidType(int id) : PommeNode(id) {
  }
  ASTPommeVoidType::ASTPommeVoidType(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeVoidType::~ASTPommeVoidType() {
  }

  /** Accept the visitor. **/
  void  ASTPommeVoidType::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
