/* Generated By:JJTree: Do not edit this line. ASTPommeConstant.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeConstant.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeConstant::ASTPommeConstant(int id) : PommeNode(id) {
  }
  ASTPommeConstant::ASTPommeConstant(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeConstant::~ASTPommeConstant() {
  }

  /** Accept the visitor. **/
  void  ASTPommeConstant::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
