/* Generated By:JJTree: Do not edit this line. ASTPommeModdedClass.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeModdedClass.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeModdedClass::ASTPommeModdedClass(int id) : PommeNode(id) {
  }
  ASTPommeModdedClass::ASTPommeModdedClass(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeModdedClass::~ASTPommeModdedClass() {
  }

  /** Accept the visitor. **/
  void  ASTPommeModdedClass::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
