/* Generated By:JJTree: Do not edit this line. ASTPommeAddEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAddEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAddEq::ASTPommeAddEq(int id) : PommeNode(id) {
  }
  ASTPommeAddEq::ASTPommeAddEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAddEq::~ASTPommeAddEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAddEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
