/* Generated By:JJTree: Do not edit this line. ASTPommeExnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeExnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeExnil::ASTPommeExnil(int id) : PommeNode(id) {
  }
  ASTPommeExnil::ASTPommeExnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeExnil::~ASTPommeExnil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeExnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
