/* Generated By:JJTree: Do not edit this line. ASTPommeModulo.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeModulo.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeModulo::ASTPommeModulo(int id) : PommeNode(id) {
  }
  ASTPommeModulo::ASTPommeModulo(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeModulo::~ASTPommeModulo() {
  }

  /** Accept the visitor. **/
  void  ASTPommeModulo::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
