/* Generated By:JJTree: Do not edit this line. ASTPommeSwinil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeSwinil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeSwinil::ASTPommeSwinil(int id) : PommeNode(id) {
  }
  ASTPommeSwinil::ASTPommeSwinil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeSwinil::~ASTPommeSwinil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeSwinil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
