/* Generated By:JJTree: Do not edit this line. ASTPommeShiftREq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeShiftREq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeShiftREq::ASTPommeShiftREq(int id) : PommeNode(id) {
  }
  ASTPommeShiftREq::ASTPommeShiftREq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeShiftREq::~ASTPommeShiftREq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeShiftREq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
