/* Generated By:JJTree: Do not edit this line. ASTPommeListExp.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeListExp.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeListExp::ASTPommeListExp(int id) : PommeNode(id) {
  }
  ASTPommeListExp::ASTPommeListExp(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeListExp::~ASTPommeListExp() {
  }

  /** Accept the visitor. **/
  void  ASTPommeListExp::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
