/* Generated By:JJTree: Do not edit this line. ASTPommeAdd.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAdd.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAdd::ASTPommeAdd(int id) : PommeNode(id) {
  }
  ASTPommeAdd::ASTPommeAdd(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAdd::~ASTPommeAdd() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAdd::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
