/* Generated By:JJTree: Do not edit this line. ASTPommeClass.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeClass.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeClass::ASTPommeClass(int id) : PommeNode(id) {
  }
  ASTPommeClass::ASTPommeClass(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeClass::~ASTPommeClass() {
  }

  /** Accept the visitor. **/
  void  ASTPommeClass::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
