/* Generated By:JJTree: Do not edit this line. ASTPommeAssign.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAssign.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAssign::ASTPommeAssign(int id) : PommeNode(id) {
  }
  ASTPommeAssign::ASTPommeAssign(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAssign::~ASTPommeAssign() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAssign::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
