/* Generated By:JJTree: Do not edit this line. ASTPommeDecrPost.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDecrPost.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDecrPost::ASTPommeDecrPost(int id) : PommeNode(id) {
  }
  ASTPommeDecrPost::ASTPommeDecrPost(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDecrPost::~ASTPommeDecrPost() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDecrPost::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
