/* Generated By:JJTree: Do not edit this line. ASTassignement.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTassignement_H_
#define ASTassignement_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTassignement : public PommeNode {
public: 
           ASTassignement(int id);
           ASTassignement(PommeLexer *parser, int id);
  virtual ~ASTassignement();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
