/* Generated By:JJTree: Do not edit this line. ASTandeq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTandeq_H_
#define ASTandeq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTandeq : public PommeNode {
public: 
           ASTandeq(int id);
           ASTandeq(PommeLexer *parser, int id);
  virtual ~ASTandeq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
