/* Generated By:JJTree: Do not edit this line. ASTacnil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTacnil_H_
#define ASTacnil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTacnil : public PommeNode {
public: 
           ASTacnil(int id);
           ASTacnil(PommeLexer *parser, int id);
  virtual ~ASTacnil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
