/* Generated By:JJTree: Do not edit this line. ASTaccessTab.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTaccessTab.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTaccessTab::ASTaccessTab(int id) : PommeNode(id) {
  }
  ASTaccessTab::ASTaccessTab(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTaccessTab::~ASTaccessTab() {
  }

  /** Accept the visitor. **/
  void  ASTaccessTab::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
