/* Generated By:JJTree: Do not edit this line. ASTassignement.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTassignement.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTassignement::ASTassignement(int id) : PommeNode(id) {
  }
  ASTassignement::ASTassignement(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTassignement::~ASTassignement() {
  }

  /** Accept the visitor. **/
  void  ASTassignement::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
