/* Generated By:JJTree: Do not edit this line. ASTdecrementPost.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTdecrementPost.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTdecrementPost::ASTdecrementPost(int id) : PommeNode(id) {
  }
  ASTdecrementPost::ASTdecrementPost(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTdecrementPost::~ASTdecrementPost() {
  }

  /** Accept the visitor. **/
  void  ASTdecrementPost::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
