/* Generated By:JJTree: Do not edit this line. ASTdiveq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTdiveq_H_
#define ASTdiveq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTdiveq : public PommeNode {
public: 
           ASTdiveq(int id);
           ASTdiveq(PommeLexer *parser, int id);
  virtual ~ASTdiveq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
