/* Generated By:JJTree: Do not edit this line. ASTdnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTdnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTdnil::ASTdnil(int id) : PommeNode(id) {
  }
  ASTdnil::ASTdnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTdnil::~ASTdnil() {
  }

  /** Accept the visitor. **/
  void  ASTdnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
