/* Generated By:JJTree: Do not edit this line. ASTdeclenums.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTdeclenums_H_
#define ASTdeclenums_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTdeclenums : public PommeNode {
public: 
           ASTdeclenums(int id);
           ASTdeclenums(PommeLexer *parser, int id);
  virtual ~ASTdeclenums();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
