/* Generated By:JJTree: Do not edit this line. ASTdecrementPre.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTdecrementPre.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTdecrementPre::ASTdecrementPre(int id) : PommeNode(id) {
  }
  ASTdecrementPre::ASTdecrementPre(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTdecrementPre::~ASTdecrementPre() {
  }

  /** Accept the visitor. **/
  void  ASTdecrementPre::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
