/* Generated By:JJTree: Do not edit this line. ASTdeclenums.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTdeclenums.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTdeclenums::ASTdeclenums(int id) : PommeNode(id) {
  }
  ASTdeclenums::ASTdeclenums(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTdeclenums::~ASTdeclenums() {
  }

  /** Accept the visitor. **/
  void  ASTdeclenums::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
