/* Generated By:JJTree: Do not edit this line. ASTdiveq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTdiveq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTdiveq::ASTdiveq(int id) : PommeNode(id) {
  }
  ASTdiveq::ASTdiveq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTdiveq::~ASTdiveq() {
  }

  /** Accept the visitor. **/
  void  ASTdiveq::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
