/* Generated By:JJTree: Do not edit this line. ASTennil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTennil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTennil::ASTennil(int id) : PommeNode(id) {
  }
  ASTennil::ASTennil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTennil::~ASTennil() {
  }

  /** Accept the visitor. **/
  void  ASTennil::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
