/* Generated By:JJTree: Do not edit this line. ASTennil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTennil_H_
#define ASTennil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTennil : public PommeNode {
public: 
           ASTennil(int id);
           ASTennil(PommeLexer *parser, int id);
  virtual ~ASTennil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
