/* Generated By:JJTree: Do not edit this line. ASTenumdefault.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTenumdefault_H_
#define ASTenumdefault_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTenumdefault : public PommeNode {
public: 
           ASTenumdefault(int id);
           ASTenumdefault(PommeLexer *parser, int id);
  virtual ~ASTenumdefault();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
