/* Generated By:JJTree: Do not edit this line. ASTenil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTenil_H_
#define ASTenil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTenil : public PommeNode {
public: 
           ASTenil(int id);
           ASTenil(PommeLexer *parser, int id);
  virtual ~ASTenil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
