/* Generated By:JJTree: Do not edit this line. ASTenumassign.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTenumassign_H_
#define ASTenumassign_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTenumassign : public PommeNode {
public: 
           ASTenumassign(int id);
           ASTenumassign(PommeLexer *parser, int id);
  virtual ~ASTenumassign();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
