/* Generated By:JJTree: Do not edit this line. ASTheader.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTheader.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTheader::ASTheader(int id) : PommeNode(id) {
  }
  ASTheader::ASTheader(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTheader::~ASTheader() {
  }

  /** Accept the visitor. **/
  void  ASTheader::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
