/* Generated By:JJTree: Do not edit this line. ASTinput.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTinput_H_
#define ASTinput_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTinput : public PommeNode {
public: 
           ASTinput(int id);
           ASTinput(PommeLexer *parser, int id);
  virtual ~ASTinput();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
