/* Generated By:JJTree: Do not edit this line. ASTincrementPre.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTincrementPre_H_
#define ASTincrementPre_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTincrementPre : public PommeNode {
public: 
           ASTincrementPre(int id);
           ASTincrementPre(PommeLexer *parser, int id);
  virtual ~ASTincrementPre();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
