/* Generated By:JJTree: Do not edit this line. ASTinil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTinil_H_
#define ASTinil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTinil : public PommeNode {
public: 
           ASTinil(int id);
           ASTinil(PommeLexer *parser, int id);
  virtual ~ASTinil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
