/* Generated By:JJTree: Do not edit this line. ASTidentOp.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTidentOp.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTidentOp::ASTidentOp(int id) : PommeNode(id) {
  }
  ASTidentOp::ASTidentOp(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTidentOp::~ASTidentOp() {
  }

  /** Accept the visitor. **/
  void  ASTidentOp::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
