/* Generated By:JJTree: Do not edit this line. ASTincrementPost.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTincrementPost.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTincrementPost::ASTincrementPost(int id) : PommeNode(id) {
  }
  ASTincrementPost::ASTincrementPost(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTincrementPost::~ASTincrementPost() {
  }

  /** Accept the visitor. **/
  void  ASTincrementPost::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
