/* Generated By:JJTree: Do not edit this line. ASTidentFuncs.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTidentFuncs.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTidentFuncs::ASTidentFuncs(int id) : PommeNode(id) {
  }
  ASTidentFuncs::ASTidentFuncs(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTidentFuncs::~ASTidentFuncs() {
  }

  /** Accept the visitor. **/
  void  ASTidentFuncs::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
