/* Generated By:JJTree: Do not edit this line. ASTinstrs.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTinstrs_H_
#define ASTinstrs_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTinstrs : public PommeNode {
public: 
           ASTinstrs(int id);
           ASTinstrs(PommeLexer *parser, int id);
  virtual ~ASTinstrs();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
