/* Generated By:JJTree: Do not edit this line. ASTident.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTident.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTident::ASTident(int id) : PommeNode(id) {
  }
  ASTident::ASTident(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTident::~ASTident() {
  }

  /** Accept the visitor. **/
  void  ASTident::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
