/* Generated By:JJTree: Do not edit this line. ASTincrementPre.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTincrementPre.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTincrementPre::ASTincrementPre(int id) : PommeNode(id) {
  }
  ASTincrementPre::ASTincrementPre(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTincrementPre::~ASTincrementPre() {
  }

  /** Accept the visitor. **/
  void  ASTincrementPre::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
