/* Generated By:JJTree: Do not edit this line. ASTlistaccesP.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTlistaccesP.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTlistaccesP::ASTlistaccesP(int id) : PommeNode(id) {
  }
  ASTlistaccesP::ASTlistaccesP(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTlistaccesP::~ASTlistaccesP() {
  }

  /** Accept the visitor. **/
  void  ASTlistaccesP::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
