/* Generated By:JJTree: Do not edit this line. ASTlistexp.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTlistexp_H_
#define ASTlistexp_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTlistexp : public PommeNode {
public: 
           ASTlistexp(int id);
           ASTlistexp(PommeLexer *parser, int id);
  virtual ~ASTlistexp();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  bool convert = false;
  std::string convertTo = "";
  uint16_t index = 0u;
  bool native = false;
};

}

#endif
