/* Generated By:JJTree: Do not edit this line. ASTlistaccess.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTlistaccess.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTlistaccess::ASTlistaccess(int id) : PommeNode(id) {
  }
  ASTlistaccess::ASTlistaccess(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTlistaccess::~ASTlistaccess() {
  }

  /** Accept the visitor. **/
  void  ASTlistaccess::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
