/* Generated By:JJTree: Do not edit this line. ASTlistacces.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTlistacces_H_
#define ASTlistacces_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTlistacces : public PommeNode {
public: 
           ASTlistacces(int id);
           ASTlistacces(PommeLexer *parser, int id);
  virtual ~ASTlistacces();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
