/* Generated By:JJTree: Do not edit this line. ASTlistaccesP.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTlistaccesP_H_
#define ASTlistaccesP_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTlistaccesP : public PommeNode {
public: 
           ASTlistaccesP(int id);
           ASTlistaccesP(PommeLexer *parser, int id);
  virtual ~ASTlistaccesP();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
