/* Generated By:JJTree: Do not edit this line. ASTlistexp.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTlistexp.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTlistexp::ASTlistexp(int id) : PommeNode(id) {
  }
  ASTlistexp::ASTlistexp(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTlistexp::~ASTlistexp() {
  }

  /** Accept the visitor. **/
  void  ASTlistexp::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
