/* Generated By:JJTree: Do not edit this line. ASTlistaccessP.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTlistaccessP.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTlistaccessP::ASTlistaccessP(int id) : PommeNode(id) {
  }
  ASTlistaccessP::ASTlistaccessP(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTlistaccessP::~ASTlistaccessP() {
  }

  /** Accept the visitor. **/
  void  ASTlistaccessP::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
