/* Generated By:JJTree: Do not edit this line. ASTmulteq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTmulteq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTmulteq::ASTmulteq(int id) : PommeNode(id) {
  }
  ASTmulteq::ASTmulteq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTmulteq::~ASTmulteq() {
  }

  /** Accept the visitor. **/
  void  ASTmulteq::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
