/* Generated By:JJTree: Do not edit this line. ASTminuseq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTminuseq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTminuseq::ASTminuseq(int id) : PommeNode(id) {
  }
  ASTminuseq::ASTminuseq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTminuseq::~ASTminuseq() {
  }

  /** Accept the visitor. **/
  void  ASTminuseq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
