/* Generated By:JJTree: Do not edit this line. ASTomega.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTomega_H_
#define ASTomega_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTomega : public PommeNode {
public: 
           ASTomega(int id);
           ASTomega(PommeLexer *parser, int id);
  virtual ~ASTomega();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
