/* Generated By:JJTree: Do not edit this line. ASTonil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTonil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTonil::ASTonil(int id) : PommeNode(id) {
  }
  ASTonil::ASTonil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTonil::~ASTonil() {
  }

  /** Accept the visitor. **/
  void  ASTonil::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
