/* Generated By:JJTree: Do not edit this line. ASToreq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASToreq_H_
#define ASToreq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASToreq : public PommeNode {
public: 
           ASToreq(int id);
           ASToreq(PommeLexer *parser, int id);
  virtual ~ASToreq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
