/* Generated By:JJTree: Do not edit this line. ASTomega.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTomega.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTomega::ASTomega(int id) : PommeNode(id) {
  }
  ASTomega::ASTomega(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTomega::~ASTomega() {
  }

  /** Accept the visitor. **/
  void  ASTomega::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
