/* Generated By:JJTree: Do not edit this line. ASToreq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASToreq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASToreq::ASToreq(int id) : PommeNode(id) {
  }
  ASToreq::ASToreq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASToreq::~ASToreq() {
  }

  /** Accept the visitor. **/
  void  ASToreq::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
