/* Generated By:JJTree: Do not edit this line. ASTpommeModulo.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeModulo.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeModulo::ASTpommeModulo(int id) : PommeNode(id) {
  }
  ASTpommeModulo::ASTpommeModulo(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeModulo::~ASTpommeModulo() {
  }

  /** Accept the visitor. **/
  void  ASTpommeModulo::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
