/* Generated By:JJTree: Do not edit this line. ASTPommeHeader.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeHeader_H_
#define ASTPommeHeader_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeHeader : public PommeNode {
public: 
           ASTPommeHeader(int id);
           ASTPommeHeader(PommeLexer *parser, int id);
  virtual ~ASTPommeHeader();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
