/* Generated By:JJTree: Do not edit this line. ASTPommeConstHeader.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeConstHeader.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeConstHeader::ASTPommeConstHeader(int id) : PommeNode(id) {
  }
  ASTPommeConstHeader::ASTPommeConstHeader(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeConstHeader::~ASTPommeConstHeader() {
  }

  /** Accept the visitor. **/
  void  ASTPommeConstHeader::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
