/* Generated By:JJTree: Do not edit this line. ASTPommeNull.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeNull_H_
#define ASTPommeNull_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeNull : public PommeNode {
public: 
           ASTPommeNull(int id);
           ASTPommeNull(PommeLexer *parser, int id);
  virtual ~ASTPommeNull();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
