/* Generated By:JJTree: Do not edit this line. ASTPommeWhile.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeWhile.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeWhile::ASTPommeWhile(int id) : PommeNode(id) {
  }
  ASTPommeWhile::ASTPommeWhile(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeWhile::~ASTPommeWhile() {
  }

  /** Accept the visitor. **/
  void  ASTPommeWhile::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
