/* Generated By:JJTree: Do not edit this line. ASTpommeModdedEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeModdedEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeModdedEnum::ASTpommeModdedEnum(int id) : PommeNode(id) {
  }
  ASTpommeModdedEnum::ASTpommeModdedEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeModdedEnum::~ASTpommeModdedEnum() {
  }

  /** Accept the visitor. **/
  void  ASTpommeModdedEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
