/* Generated By:JJTree: Do not edit this line. ASTPommeVinil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeVinil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeVinil::ASTPommeVinil(int id) : PommeNode(id) {
  }
  ASTPommeVinil::ASTPommeVinil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeVinil::~ASTPommeVinil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeVinil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
