/* Generated By:JJTree: Do not edit this line. ASTpommeClass.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeClass.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeClass::ASTpommeClass(int id) : PommeNode(id) {
  }
  ASTpommeClass::ASTpommeClass(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeClass::~ASTpommeClass() {
  }

  /** Accept the visitor. **/
  void  ASTpommeClass::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
