/* Generated By:JJTree: Do not edit this line. ASTPommeAddEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeAddEq_H_
#define ASTPommeAddEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeAddEq : public PommeNode {
public: 
           ASTPommeAddEq(int id);
           ASTPommeAddEq(PommeLexer *parser, int id);
  virtual ~ASTPommeAddEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
