/* Generated By:JJTree: Do not edit this line. ASTpommeClassChild.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeClassChild_H_
#define ASTpommeClassChild_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeClassChild : public PommeNode {
public: 
           ASTpommeClassChild(int id);
           ASTpommeClassChild(PommeLexer *parser, int id);
  virtual ~ASTpommeClassChild();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
