/* Generated By:JJTree: Do not edit this line. ASTpommeTypeDef.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeTypeDef.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeTypeDef::ASTpommeTypeDef(int id) : PommeNode(id) {
  }
  ASTpommeTypeDef::ASTpommeTypeDef(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeTypeDef::~ASTpommeTypeDef() {
  }

  /** Accept the visitor. **/
  void  ASTpommeTypeDef::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
