/* Generated By:JJTree: Do not edit this line. ASTPommeDelete.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDelete.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDelete::ASTPommeDelete(int id) : PommeNode(id) {
  }
  ASTPommeDelete::ASTPommeDelete(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDelete::~ASTPommeDelete() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDelete::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
