/* Generated By:JJTree: Do not edit this line. ASTPommeGET.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeGET.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeGET::ASTPommeGET(int id) : PommeNode(id) {
  }
  ASTPommeGET::ASTPommeGET(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeGET::~ASTPommeGET() {
  }

  /** Accept the visitor. **/
  void  ASTPommeGET::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
