/* Generated By:JJTree: Do not edit this line. ASTpommeInt.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeInt_H_
#define ASTpommeInt_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeInt : public PommeNode {
public: 
           ASTpommeInt(int id);
           ASTpommeInt(PommeLexer *parser, int id);
  virtual ~ASTpommeInt();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  int64_t m_Value;
};

}

#endif
