/* Generated By:JJTree: Do not edit this line. ASTpommeDiv.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeDiv.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeDiv::ASTpommeDiv(int id) : PommeNode(id) {
  }
  ASTpommeDiv::ASTpommeDiv(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeDiv::~ASTpommeDiv() {
  }

  /** Accept the visitor. **/
  void  ASTpommeDiv::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
