/* Generated By:JJTree: Do not edit this line. ASTPommeVarDecls.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeVarDecls.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeVarDecls::ASTPommeVarDecls(int id) : PommeNode(id) {
  }
  ASTPommeVarDecls::ASTPommeVarDecls(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeVarDecls::~ASTPommeVarDecls() {
  }

  /** Accept the visitor. **/
  void  ASTPommeVarDecls::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
