/* Generated By:JJTree: Do not edit this line. ASTPommeNot.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeNot.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeNot::ASTPommeNot(int id) : PommeNode(id) {
  }
  ASTPommeNot::ASTPommeNot(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeNot::~ASTPommeNot() {
  }

  /** Accept the visitor. **/
  void  ASTPommeNot::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
