/* Generated By:JJTree: Do not edit this line. ASTPommeStatic.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeStatic_H_
#define ASTPommeStatic_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeStatic : public PommeNode {
public: 
           ASTPommeStatic(int id);
           ASTPommeStatic(PommeLexer *parser, int id);
  virtual ~ASTPommeStatic();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
