/* Generated By:JJTree: Do not edit this line. ASTPommeGET.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeGET_H_
#define ASTPommeGET_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeGET : public PommeNode {
public: 
           ASTPommeGET(int id);
           ASTPommeGET(PommeLexer *parser, int id);
  virtual ~ASTPommeGET();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
