/* Generated By:JJTree: Do not edit this line. ASTPommeTrue.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeTrue.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeTrue::ASTPommeTrue(int id) : PommeNode(id) {
  }
  ASTPommeTrue::ASTPommeTrue(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeTrue::~ASTPommeTrue() {
  }

  /** Accept the visitor. **/
  void  ASTPommeTrue::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
