/* Generated By:JJTree: Do not edit this line. ASTPommePrivate.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommePrivate_H_
#define ASTPommePrivate_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommePrivate : public PommeNode {
public: 
           ASTPommePrivate(int id);
           ASTPommePrivate(PommeLexer *parser, int id);
  virtual ~ASTPommePrivate();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
