/* Generated By:JJTree: Do not edit this line. ASTPommeAndEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAndEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAndEq::ASTPommeAndEq(int id) : PommeNode(id) {
  }
  ASTPommeAndEq::ASTPommeAndEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAndEq::~ASTPommeAndEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAndEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
