/* Generated By:JJTree: Do not edit this line. ASTPommeDefault.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDefault_H_
#define ASTPommeDefault_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDefault : public PommeNode {
public: 
           ASTPommeDefault(int id);
           ASTPommeDefault(PommeLexer *parser, int id);
  virtual ~ASTPommeDefault();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
