/* Generated By:JJTree: Do not edit this line. ASTpommeOverride.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeOverride_H_
#define ASTpommeOverride_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeOverride : public PommeNode {
public: 
           ASTpommeOverride(int id);
           ASTpommeOverride(PommeLexer *parser, int id);
  virtual ~ASTpommeOverride();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
