/* Generated By:JJTree: Do not edit this line. ASTpommePrint.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommePrint.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommePrint::ASTpommePrint(int id) : PommeNode(id) {
  }
  ASTpommePrint::ASTpommePrint(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommePrint::~ASTpommePrint() {
  }

  /** Accept the visitor. **/
  void  ASTpommePrint::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
