/* Generated By:JJTree: Do not edit this line. ASTPommeMethodeNative.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeMethodeNative.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeMethodeNative::ASTPommeMethodeNative(int id) : PommeNode(id) {
  }
  ASTPommeMethodeNative::ASTPommeMethodeNative(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeMethodeNative::~ASTPommeMethodeNative() {
  }

  /** Accept the visitor. **/
  void  ASTPommeMethodeNative::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
