/* Generated By:JJTree: Do not edit this line. ASTPommeIdentFuncs.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeIdentFuncs.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeIdentFuncs::ASTPommeIdentFuncs(int id) : PommeNode(id) {
  }
  ASTPommeIdentFuncs::ASTPommeIdentFuncs(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeIdentFuncs::~ASTPommeIdentFuncs() {
  }

  /** Accept the visitor. **/
  void  ASTPommeIdentFuncs::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
