/* Generated By:JJTree: Do not edit this line. ASTpommePrivate.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommePrivate_H_
#define ASTpommePrivate_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommePrivate : public PommeNode {
public: 
           ASTpommePrivate(int id);
           ASTpommePrivate(PommeLexer *parser, int id);
  virtual ~ASTpommePrivate();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
