/* Generated By:JJTree: Do not edit this line. ASTPommeModdedEnum.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeModdedEnum_H_
#define ASTPommeModdedEnum_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeModdedEnum : public PommeNode {
public: 
           ASTPommeModdedEnum(int id);
           ASTPommeModdedEnum(PommeLexer *parser, int id);
  virtual ~ASTPommeModdedEnum();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
