/* Generated By:JJTree: Do not edit this line. ASTPommeNEQ.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeNEQ.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeNEQ::ASTPommeNEQ(int id) : PommeNode(id) {
  }
  ASTPommeNEQ::ASTPommeNEQ(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeNEQ::~ASTPommeNEQ() {
  }

  /** Accept the visitor. **/
  void  ASTPommeNEQ::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
