/* Generated By:JJTree: Do not edit this line. ASTpommeBreak.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeBreak_H_
#define ASTpommeBreak_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeBreak : public PommeNode {
public: 
           ASTpommeBreak(int id);
           ASTpommeBreak(PommeLexer *parser, int id);
  virtual ~ASTpommeBreak();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
