/* Generated By:JJTree: Do not edit this line. ASTpommeIf.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeIf.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeIf::ASTpommeIf(int id) : PommeNode(id) {
  }
  ASTpommeIf::ASTpommeIf(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeIf::~ASTpommeIf() {
  }

  /** Accept the visitor. **/
  void  ASTpommeIf::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
