/* Generated By:JJTree: Do not edit this line. ASTpommePublic.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommePublic_H_
#define ASTpommePublic_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommePublic : public PommeNode {
public: 
           ASTpommePublic(int id);
           ASTpommePublic(PommeLexer *parser, int id);
  virtual ~ASTpommePublic();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
