/* Generated By:JJTree: Do not edit this line. ASTpommeUnary.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeUnary.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeUnary::ASTpommeUnary(int id) : PommeNode(id) {
  }
  ASTpommeUnary::ASTpommeUnary(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeUnary::~ASTpommeUnary() {
  }

  /** Accept the visitor. **/
  void  ASTpommeUnary::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
