/* Generated By:JJTree: Do not edit this line. ASTPommeListAccess.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeListAccess.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeListAccess::ASTPommeListAccess(int id) : PommeNode(id) {
  }
  ASTPommeListAccess::ASTPommeListAccess(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeListAccess::~ASTPommeListAccess() {
  }

  /** Accept the visitor. **/
  void  ASTPommeListAccess::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
