/* Generated By:JJTree: Do not edit this line. ASTPommeShiftL.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeShiftL.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeShiftL::ASTPommeShiftL(int id) : PommeNode(id) {
  }
  ASTPommeShiftL::ASTPommeShiftL(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeShiftL::~ASTPommeShiftL() {
  }

  /** Accept the visitor. **/
  void  ASTPommeShiftL::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
