/* Generated By:JJTree: Do not edit this line. ASTPommeMethode.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeMethode.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeMethode::ASTPommeMethode(int id) : PommeNode(id) {
  }
  ASTPommeMethode::ASTPommeMethode(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeMethode::~ASTPommeMethode() {
  }

  /** Accept the visitor. **/
  void  ASTPommeMethode::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
