/* Generated By:JJTree: Do not edit this line. ASTPommeHeaders.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeHeaders.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeHeaders::ASTPommeHeaders(int id) : PommeNode(id) {
  }
  ASTPommeHeaders::ASTPommeHeaders(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeHeaders::~ASTPommeHeaders() {
  }

  /** Accept the visitor. **/
  void  ASTPommeHeaders::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
