/* Generated By:JJTree: Do not edit this line. ASTPommeDelete.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDelete_H_
#define ASTPommeDelete_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDelete : public PommeNode {
public: 
           ASTPommeDelete(int id);
           ASTPommeDelete(PommeLexer *parser, int id);
  virtual ~ASTPommeDelete();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
