/* Generated By:JJTree: Do not edit this line. ASTpommeArray.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeArray.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeArray::ASTpommeArray(int id) : PommeNode(id) {
  }
  ASTpommeArray::ASTpommeArray(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeArray::~ASTpommeArray() {
  }

  /** Accept the visitor. **/
  void  ASTpommeArray::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
