/* Generated By:JJTree: Do not edit this line. ASTPommeConstHeader.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeConstHeader_H_
#define ASTPommeConstHeader_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeConstHeader : public PommeNode {
public: 
           ASTPommeConstHeader(int id);
           ASTPommeConstHeader(PommeLexer *parser, int id);
  virtual ~ASTPommeConstHeader();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
