/* Generated By:JJTree: Do not edit this line. ASTpommeNull.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeNull.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeNull::ASTpommeNull(int id) : PommeNode(id) {
  }
  ASTpommeNull::ASTpommeNull(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeNull::~ASTpommeNull() {
  }

  /** Accept the visitor. **/
  void  ASTpommeNull::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
