/* Generated By:JJTree: Do not edit this line. ASTpommeCases.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeCases_H_
#define ASTpommeCases_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeCases : public PommeNode {
public: 
           ASTpommeCases(int id);
           ASTpommeCases(PommeLexer *parser, int id);
  virtual ~ASTpommeCases();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
