/* Generated By:JJTree: Do not edit this line. ASTpommeTilde.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeTilde.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeTilde::ASTpommeTilde(int id) : PommeNode(id) {
  }
  ASTpommeTilde::ASTpommeTilde(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeTilde::~ASTpommeTilde() {
  }

  /** Accept the visitor. **/
  void  ASTpommeTilde::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
