/* Generated By:JJTree: Do not edit this line. ASTpommeShiftR.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeShiftR.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeShiftR::ASTpommeShiftR(int id) : PommeNode(id) {
  }
  ASTpommeShiftR::ASTpommeShiftR(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeShiftR::~ASTpommeShiftR() {
  }

  /** Accept the visitor. **/
  void  ASTpommeShiftR::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
