/* Generated By:JJTree: Do not edit this line. ASTPommeCase.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeCase_H_
#define ASTPommeCase_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeCase : public PommeNode {
public: 
           ASTPommeCase(int id);
           ASTPommeCase(PommeLexer *parser, int id);
  virtual ~ASTPommeCase();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
