/* Generated By:JJTree: Do not edit this line. ASTPommeModdedEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeModdedEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeModdedEnum::ASTPommeModdedEnum(int id) : PommeNode(id) {
  }
  ASTPommeModdedEnum::ASTPommeModdedEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeModdedEnum::~ASTPommeModdedEnum() {
  }

  /** Accept the visitor. **/
  void  ASTPommeModdedEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
