/* Generated By:JJTree: Do not edit this line. ASTPommeIdent.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeIdent_H_
#define ASTPommeIdent_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeIdent : public PommeNode {
public: 
           ASTPommeIdent(int id);
           ASTPommeIdent(PommeLexer *parser, int id);
  virtual ~ASTPommeIdent();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
  
  std::string m_Identifier;
  std::string m_MethodIdentifier;
  uint16_t m_IndexAttribute = 0;
  bool m_Attribute = false;
  bool m_Super = false;
};

}

#endif
