/* Generated By:JJTree: Do not edit this line. ASTpommeGET.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeGET_H_
#define ASTpommeGET_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeGET : public PommeNode {
public: 
           ASTpommeGET(int id);
           ASTpommeGET(PommeLexer *parser, int id);
  virtual ~ASTpommeGET();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
