/* Generated By:JJTree: Do not edit this line. ASTPommeSnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeSnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeSnil::ASTPommeSnil(int id) : PommeNode(id) {
  }
  ASTPommeSnil::ASTPommeSnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeSnil::~ASTPommeSnil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeSnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
