/* Generated By:JJTree: Do not edit this line. ASTpommeStatic.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeStatic.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeStatic::ASTpommeStatic(int id) : PommeNode(id) {
  }
  ASTpommeStatic::ASTpommeStatic(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeStatic::~ASTpommeStatic() {
  }

  /** Accept the visitor. **/
  void  ASTpommeStatic::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
