/* Generated By:JJTree: Do not edit this line. ASTpommeExtendsEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeExtendsEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeExtendsEnum::ASTpommeExtendsEnum(int id) : PommeNode(id) {
  }
  ASTpommeExtendsEnum::ASTpommeExtendsEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeExtendsEnum::~ASTpommeExtendsEnum() {
  }

  /** Accept the visitor. **/
  void  ASTpommeExtendsEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
