/* Generated By:JJTree: Do not edit this line. ASTpommeNull.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeNull_H_
#define ASTpommeNull_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeNull : public PommeNode {
public: 
           ASTpommeNull(int id);
           ASTpommeNull(PommeLexer *parser, int id);
  virtual ~ASTpommeNull();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
