/* Generated By:JJTree: Do not edit this line. ASTpommeDestructor.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeDestructor_H_
#define ASTpommeDestructor_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeDestructor : public PommeNode {
public: 
           ASTpommeDestructor(int id);
           ASTpommeDestructor(PommeLexer *parser, int id);
  virtual ~ASTpommeDestructor();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
