/* Generated By:JJTree: Do not edit this line. ASTPommeFloat.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeFloat.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeFloat::ASTPommeFloat(int id) : PommeNode(id) {
  }
  ASTPommeFloat::ASTPommeFloat(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeFloat::~ASTPommeFloat() {
  }

  /** Accept the visitor. **/
  void  ASTPommeFloat::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
