/* Generated By:JJTree: Do not edit this line. ASTpommeProperty.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeProperty.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeProperty::ASTpommeProperty(int id) : PommeNode(id) {
  }
  ASTpommeProperty::ASTpommeProperty(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeProperty::~ASTpommeProperty() {
  }

  /** Accept the visitor. **/
  void  ASTpommeProperty::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
