/* Generated By:JJTree: Do not edit this line. ASTPommeString.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeString.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeString::ASTPommeString(int id) : PommeNode(id) {
  }
  ASTPommeString::ASTPommeString(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeString::~ASTPommeString() {
  }

  /** Accept the visitor. **/
  void  ASTPommeString::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
