/* Generated By:JJTree: Do not edit this line. ASTPommeDestructor.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDestructor_H_
#define ASTPommeDestructor_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDestructor : public PommeNode {
public: 
           ASTPommeDestructor(int id);
           ASTPommeDestructor(PommeLexer *parser, int id);
  virtual ~ASTPommeDestructor();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
