/* Generated By:JJTree: Do not edit this line. ASTpommeReturn.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeReturn.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeReturn::ASTpommeReturn(int id) : PommeNode(id) {
  }
  ASTpommeReturn::ASTpommeReturn(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeReturn::~ASTpommeReturn() {
  }

  /** Accept the visitor. **/
  void  ASTpommeReturn::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
