/* Generated By:JJTree: Do not edit this line. ASTpommeGET.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeGET.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeGET::ASTpommeGET(int id) : PommeNode(id) {
  }
  ASTpommeGET::ASTpommeGET(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeGET::~ASTpommeGET() {
  }

  /** Accept the visitor. **/
  void  ASTpommeGET::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
