/* Generated By:JJTree: Do not edit this line. ASTPommeMinusEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeMinusEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeMinusEq::ASTPommeMinusEq(int id) : PommeNode(id) {
  }
  ASTPommeMinusEq::ASTPommeMinusEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeMinusEq::~ASTPommeMinusEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeMinusEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
