/* Generated By:JJTree: Do not edit this line. ASTpommeOverride.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeOverride.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeOverride::ASTpommeOverride(int id) : PommeNode(id) {
  }
  ASTpommeOverride::ASTpommeOverride(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeOverride::~ASTpommeOverride() {
  }

  /** Accept the visitor. **/
  void  ASTpommeOverride::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
