/* Generated By:JJTree: Do not edit this line. ASTpommeShiftL.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeShiftL_H_
#define ASTpommeShiftL_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeShiftL : public PommeNode {
public: 
           ASTpommeShiftL(int id);
           ASTpommeShiftL(PommeLexer *parser, int id);
  virtual ~ASTpommeShiftL();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
