/* Generated By:JJTree: Do not edit this line. ASTpommeVariable.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeVariable_H_
#define ASTpommeVariable_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeVariable : public PommeNode {
public: 
           ASTpommeVariable(int id);
           ASTpommeVariable(PommeLexer *parser, int id);
  virtual ~ASTpommeVariable();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
