/* Generated By:JJTree: Do not edit this line. ASTpommeFalse.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeFalse.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeFalse::ASTpommeFalse(int id) : PommeNode(id) {
  }
  ASTpommeFalse::ASTpommeFalse(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeFalse::~ASTpommeFalse() {
  }

  /** Accept the visitor. **/
  void  ASTpommeFalse::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
