/* Generated By:JJTree: Do not edit this line. ASTPommeSwitch.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeSwitch.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeSwitch::ASTPommeSwitch(int id) : PommeNode(id) {
  }
  ASTPommeSwitch::ASTPommeSwitch(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeSwitch::~ASTPommeSwitch() {
  }

  /** Accept the visitor. **/
  void  ASTPommeSwitch::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
