/* Generated By:JJTree: Do not edit this line. ASTPommeAnd.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAnd.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAnd::ASTPommeAnd(int id) : PommeNode(id) {
  }
  ASTPommeAnd::ASTPommeAnd(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAnd::~ASTPommeAnd() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAnd::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
