/* Generated By:JJTree: Do not edit this line. ASTPommeInt.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeInt.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeInt::ASTPommeInt(int id) : PommeNode(id) {
  }
  ASTPommeInt::ASTPommeInt(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeInt::~ASTPommeInt() {
  }

  /** Accept the visitor. **/
  void  ASTPommeInt::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
