/* Generated By:JJTree: Do not edit this line. ASTpommeOr.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeOr_H_
#define ASTpommeOr_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeOr : public PommeNode {
public: 
           ASTpommeOr(int id);
           ASTpommeOr(PommeLexer *parser, int id);
  virtual ~ASTpommeOr();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
