/* Generated By:JJTree: Do not edit this line. ASTpommeConstructor.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeConstructor.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeConstructor::ASTpommeConstructor(int id) : PommeNode(id) {
  }
  ASTpommeConstructor::ASTpommeConstructor(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeConstructor::~ASTpommeConstructor() {
  }

  /** Accept the visitor. **/
  void  ASTpommeConstructor::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
