/* Generated By:JJTree: Do not edit this line. ASTPommeBreak.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeBreak_H_
#define ASTPommeBreak_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeBreak : public PommeNode {
public: 
           ASTPommeBreak(int id);
           ASTPommeBreak(PommeLexer *parser, int id);
  virtual ~ASTPommeBreak();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
