/* Generated By:JJTree: Do not edit this line. ASTPommeDecrPost.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDecrPost_H_
#define ASTPommeDecrPost_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDecrPost : public PommeNode {
public: 
           ASTPommeDecrPost(int id);
           ASTPommeDecrPost(PommeLexer *parser, int id);
  virtual ~ASTPommeDecrPost();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
