/* Generated By:JJTree: Do not edit this line. ASTPommeIncrPost.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeIncrPost.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeIncrPost::ASTPommeIncrPost(int id) : PommeNode(id) {
  }
  ASTPommeIncrPost::ASTPommeIncrPost(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeIncrPost::~ASTPommeIncrPost() {
  }

  /** Accept the visitor. **/
  void  ASTPommeIncrPost::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
