/* Generated By:JJTree: Do not edit this line. ASTpommePublic.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommePublic.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommePublic::ASTpommePublic(int id) : PommeNode(id) {
  }
  ASTpommePublic::ASTpommePublic(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommePublic::~ASTpommePublic() {
  }

  /** Accept the visitor. **/
  void  ASTpommePublic::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
