/* Generated By:JJTree: Do not edit this line. ASTPommeEnum.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeEnum_H_
#define ASTPommeEnum_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeEnum : public PommeNode {
public: 
           ASTPommeEnum(int id);
           ASTPommeEnum(PommeLexer *parser, int id);
  virtual ~ASTPommeEnum();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
