/* Generated By:JJTree: Do not edit this line. ASTPommeClassChild.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeClassChild_H_
#define ASTPommeClassChild_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeClassChild : public PommeNode {
public: 
           ASTPommeClassChild(int id);
           ASTPommeClassChild(PommeLexer *parser, int id);
  virtual ~ASTPommeClassChild();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
