/* Generated By:JJTree: Do not edit this line. ASTPommeInstrs.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeInstrs_H_
#define ASTPommeInstrs_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeInstrs : public PommeNode {
public: 
           ASTPommeInstrs(int id);
           ASTPommeInstrs(PommeLexer *parser, int id);
  virtual ~ASTPommeInstrs();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
