/* Generated By:JJTree: Do not edit this line. ASTPommeLT.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeLT_H_
#define ASTPommeLT_H_

#include "PommeNode.h"
#include "VM/Chunk.h"

namespace Pomme {
class PommeLexer;

class ASTPommeLT : public PommeNode {
public: 
           ASTPommeLT(int id);
           ASTPommeLT(PommeLexer *parser, int id);
  virtual ~ASTPommeLT();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
  bool primitive = false;
  OpCode opCode;
};

}

#endif
