/* Generated By:JJTree: Do not edit this line. ASTPommeDiv.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDiv.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDiv::ASTPommeDiv(int id) : PommeNode(id) {
  }
  ASTPommeDiv::ASTPommeDiv(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDiv::~ASTPommeDiv() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDiv::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
