/* Generated By:JJTree: Do not edit this line. ASTpommeTypeDef.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeTypeDef_H_
#define ASTpommeTypeDef_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeTypeDef : public PommeNode {
public: 
           ASTpommeTypeDef(int id);
           ASTpommeTypeDef(PommeLexer *parser, int id);
  virtual ~ASTpommeTypeDef();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
