/* Generated By:JJTree: Do not edit this line. ASTPommeInput.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeInput_H_
#define ASTPommeInput_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeInput : public PommeNode {
public: 
           ASTPommeInput(int id);
           ASTPommeInput(PommeLexer *parser, int id);
  virtual ~ASTPommeInput();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
