/* Generated By:JJTree: Do not edit this line. ASTPommeDeclEnums.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDeclEnums.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDeclEnums::ASTPommeDeclEnums(int id) : PommeNode(id) {
  }
  ASTPommeDeclEnums::ASTPommeDeclEnums(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDeclEnums::~ASTPommeDeclEnums() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDeclEnums::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
