/* Generated By:JJTree: Do not edit this line. ASTPommeOrEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeOrEq_H_
#define ASTPommeOrEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeOrEq : public PommeNode {
public: 
           ASTPommeOrEq(int id);
           ASTPommeOrEq(PommeLexer *parser, int id);
  virtual ~ASTPommeOrEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
