/* Generated By:JJTree: Do not edit this line. ASTpommeNot.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeNot.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeNot::ASTpommeNot(int id) : PommeNode(id) {
  }
  ASTpommeNot::ASTpommeNot(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeNot::~ASTpommeNot() {
  }

  /** Accept the visitor. **/
  void  ASTpommeNot::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
