/* Generated By:JJTree: Do not edit this line. ASTPommeOmega.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeOmega_H_
#define ASTPommeOmega_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeOmega : public PommeNode {
public: 
           ASTPommeOmega(int id);
           ASTPommeOmega(PommeLexer *parser, int id);
  virtual ~ASTPommeOmega();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
