/* Generated By:JJTree: Do not edit this line. ASTPommeInstrs.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeInstrs.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeInstrs::ASTPommeInstrs(int id) : PommeNode(id) {
  }
  ASTPommeInstrs::ASTPommeInstrs(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeInstrs::~ASTPommeInstrs() {
  }

  /** Accept the visitor. **/
  void  ASTPommeInstrs::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
