/* Generated By:JJTree: Do not edit this line. ASTpommeTrue.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeTrue.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeTrue::ASTpommeTrue(int id) : PommeNode(id) {
  }
  ASTpommeTrue::ASTpommeTrue(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeTrue::~ASTpommeTrue() {
  }

  /** Accept the visitor. **/
  void  ASTpommeTrue::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
