/* Generated By:JJTree: Do not edit this line. ASTpommeString.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeString_H_
#define ASTpommeString_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeString : public PommeNode {
public: 
           ASTpommeString(int id);
           ASTpommeString(PommeLexer *parser, int id);
  virtual ~ASTpommeString();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;

  std::string m_Value;
};

}

#endif
