/* Generated By:JJTree: Do not edit this line. ASTPommeDivEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeDivEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeDivEq::ASTPommeDivEq(int id) : PommeNode(id) {
  }
  ASTPommeDivEq::ASTPommeDivEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeDivEq::~ASTPommeDivEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeDivEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
