/* Generated By:JJTree: Do not edit this line. ASTPommeInil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeInil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeInil::ASTPommeInil(int id) : PommeNode(id) {
  }
  ASTPommeInil::ASTPommeInil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeInil::~ASTPommeInil() {
  }

  /** Accept the visitor. **/
  void  ASTPommeInil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
