/* Generated By:JJTree: Do not edit this line. ASTPommeIf.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeIf.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeIf::ASTPommeIf(int id) : PommeNode(id) {
  }
  ASTPommeIf::ASTPommeIf(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeIf::~ASTPommeIf() {
  }

  /** Accept the visitor. **/
  void  ASTPommeIf::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
