/* Generated By:JJTree: Do not edit this line. ASTPommeEQ.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeEQ.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeEQ::ASTPommeEQ(int id) : PommeNode(id) {
  }
  ASTPommeEQ::ASTPommeEQ(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeEQ::~ASTPommeEQ() {
  }

  /** Accept the visitor. **/
  void  ASTPommeEQ::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
