/* Generated By:JJTree: Do not edit this line. ASTPommeOverride.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeOverride.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeOverride::ASTPommeOverride(int id) : PommeNode(id) {
  }
  ASTPommeOverride::ASTPommeOverride(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeOverride::~ASTPommeOverride() {
  }

  /** Accept the visitor. **/
  void  ASTPommeOverride::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
