/* Generated By:JJTree: Do not edit this line. ASTPommeIdentFuncs.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeIdentFuncs_H_
#define ASTPommeIdentFuncs_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeIdentFuncs : public PommeNode {
public: 
           ASTPommeIdentFuncs(int id);
           ASTPommeIdentFuncs(PommeLexer *parser, int id);
  virtual ~ASTPommeIdentFuncs();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
