/* Generated By:JJTree: Do not edit this line. ASTpommePrivate.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommePrivate.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommePrivate::ASTpommePrivate(int id) : PommeNode(id) {
  }
  ASTpommePrivate::ASTpommePrivate(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommePrivate::~ASTpommePrivate() {
  }

  /** Accept the visitor. **/
  void  ASTpommePrivate::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
