/* Generated By:JJTree: Do not edit this line. ASTpommeClass.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeClass_H_
#define ASTpommeClass_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeClass : public PommeNode {
public: 
           ASTpommeClass(int id);
           ASTpommeClass(PommeLexer *parser, int id);
  virtual ~ASTpommeClass();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
