/* Generated By:JJTree: Do not edit this line. ASTpommeClassChild.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeClassChild.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeClassChild::ASTpommeClassChild(int id) : PommeNode(id) {
  }
  ASTpommeClassChild::ASTpommeClassChild(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeClassChild::~ASTpommeClassChild() {
  }

  /** Accept the visitor. **/
  void  ASTpommeClassChild::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
