/* Generated By:JJTree: Do not edit this line. ASTPommeExtendsEnum.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeExtendsEnum_H_
#define ASTPommeExtendsEnum_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeExtendsEnum : public PommeNode {
public: 
           ASTPommeExtendsEnum(int id);
           ASTPommeExtendsEnum(PommeLexer *parser, int id);
  virtual ~ASTPommeExtendsEnum();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
