/* Generated By:JJTree: Do not edit this line. ASTPommeUnary.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeUnary.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeUnary::ASTPommeUnary(int id) : PommeNode(id) {
  }
  ASTPommeUnary::ASTPommeUnary(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeUnary::~ASTPommeUnary() {
  }

  /** Accept the visitor. **/
  void  ASTPommeUnary::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
