/* Generated By:JJTree: Do not edit this line. ASTPommePrivate.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommePrivate.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommePrivate::ASTPommePrivate(int id) : PommeNode(id) {
  }
  ASTPommePrivate::ASTPommePrivate(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommePrivate::~ASTPommePrivate() {
  }

  /** Accept the visitor. **/
  void  ASTPommePrivate::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
