/* Generated By:JJTree: Do not edit this line. ASTPommeEnil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeEnil_H_
#define ASTPommeEnil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeEnil : public PommeNode {
public: 
           ASTPommeEnil(int id);
           ASTPommeEnil(PommeLexer *parser, int id);
  virtual ~ASTPommeEnil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
