/* Generated By:JJTree: Do not edit this line. ASTpommeShiftL.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeShiftL.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeShiftL::ASTpommeShiftL(int id) : PommeNode(id) {
  }
  ASTpommeShiftL::ASTpommeShiftL(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeShiftL::~ASTpommeShiftL() {
  }

  /** Accept the visitor. **/
  void  ASTpommeShiftL::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
