/* Generated By:JJTree: Do not edit this line. ASTpommeProperty.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeProperty_H_
#define ASTpommeProperty_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeProperty : public PommeNode {
public: 
           ASTpommeProperty(int id);
           ASTpommeProperty(PommeLexer *parser, int id);
  virtual ~ASTpommeProperty();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
