/* Generated By:JJTree: Do not edit this line. ASTPommeListExp.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeListExp_H_
#define ASTPommeListExp_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeListExp : public PommeNode {
public: 
           ASTPommeListExp(int id);
           ASTPommeListExp(PommeLexer *parser, int id);
  virtual ~ASTPommeListExp();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  bool convert = false;
  std::string convertTo = "";
  uint16_t index = 0u;
  bool native = false;
};

}

#endif
