/* Generated By:JJTree: Do not edit this line. ASTPommeMultEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeMultEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeMultEq::ASTPommeMultEq(int id) : PommeNode(id) {
  }
  ASTPommeMultEq::ASTPommeMultEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeMultEq::~ASTPommeMultEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeMultEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
