/* Generated By:JJTree: Do not edit this line. ASTpommeDefault.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeDefault_H_
#define ASTpommeDefault_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeDefault : public PommeNode {
public: 
           ASTpommeDefault(int id);
           ASTpommeDefault(PommeLexer *parser, int id);
  virtual ~ASTpommeDefault();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
