/* Generated By:JJTree: Do not edit this line. ASTpommeShiftR.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeShiftR_H_
#define ASTpommeShiftR_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeShiftR : public PommeNode {
public: 
           ASTpommeShiftR(int id);
           ASTpommeShiftR(PommeLexer *parser, int id);
  virtual ~ASTpommeShiftR();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
