/* Generated By:JJTree: Do not edit this line. ASTPommeExtendsEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeExtendsEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeExtendsEnum::ASTPommeExtendsEnum(int id) : PommeNode(id) {
  }
  ASTPommeExtendsEnum::ASTPommeExtendsEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeExtendsEnum::~ASTPommeExtendsEnum() {
  }

  /** Accept the visitor. **/
  void  ASTPommeExtendsEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
