/* Generated By:JJTree: Do not edit this line. ASTpommeNew.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeNew.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeNew::ASTpommeNew(int id) : PommeNode(id) {
  }
  ASTpommeNew::ASTpommeNew(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeNew::~ASTpommeNew() {
  }

  /** Accept the visitor. **/
  void  ASTpommeNew::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
