/* Generated By:JJTree: Do not edit this line. ASTpommeProtected.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeProtected.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeProtected::ASTpommeProtected(int id) : PommeNode(id) {
  }
  ASTpommeProtected::ASTpommeProtected(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeProtected::~ASTpommeProtected() {
  }

  /** Accept the visitor. **/
  void  ASTpommeProtected::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
