/* Generated By:JJTree: Do not edit this line. ASTPommeClassChild.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeClassChild.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeClassChild::ASTPommeClassChild(int id) : PommeNode(id) {
  }
  ASTPommeClassChild::ASTPommeClassChild(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeClassChild::~ASTPommeClassChild() {
  }

  /** Accept the visitor. **/
  void  ASTPommeClassChild::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
