/* Generated By:JJTree: Do not edit this line. ASTpommeNEQ.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeNEQ.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeNEQ::ASTpommeNEQ(int id) : PommeNode(id) {
  }
  ASTpommeNEQ::ASTpommeNEQ(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeNEQ::~ASTpommeNEQ() {
  }

  /** Accept the visitor. **/
  void  ASTpommeNEQ::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
