/* Generated By:JJTree: Do not edit this line. ASTPommeMethode.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeMethode_H_
#define ASTPommeMethode_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeMethode : public PommeNode {
public: 
           ASTPommeMethode(int id);
           ASTPommeMethode(PommeLexer *parser, int id);
  virtual ~ASTPommeMethode();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
