/* Generated By:JJTree: Do not edit this line. ASTPommeFalse.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeFalse.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeFalse::ASTPommeFalse(int id) : PommeNode(id) {
  }
  ASTPommeFalse::ASTPommeFalse(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeFalse::~ASTPommeFalse() {
  }

  /** Accept the visitor. **/
  void  ASTPommeFalse::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
