/* Generated By:JJTree: Do not edit this line. ASTpommeExtendsEnum.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeExtendsEnum_H_
#define ASTpommeExtendsEnum_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeExtendsEnum : public PommeNode {
public: 
           ASTpommeExtendsEnum(int id);
           ASTpommeExtendsEnum(PommeLexer *parser, int id);
  virtual ~ASTpommeExtendsEnum();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
