/* Generated By:JJTree: Do not edit this line. ASTpommeTilde.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeTilde_H_
#define ASTpommeTilde_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeTilde : public PommeNode {
public: 
           ASTpommeTilde(int id);
           ASTpommeTilde(PommeLexer *parser, int id);
  virtual ~ASTpommeTilde();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
