/* Generated By:JJTree: Do not edit this line. ASTpommeMethodeNative.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeMethodeNative.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeMethodeNative::ASTpommeMethodeNative(int id) : PommeNode(id) {
  }
  ASTpommeMethodeNative::ASTpommeMethodeNative(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeMethodeNative::~ASTpommeMethodeNative() {
  }

  /** Accept the visitor. **/
  void  ASTpommeMethodeNative::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
