/* Generated By:JJTree: Do not edit this line. ASTPommeEnumDefault.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeEnumDefault_H_
#define ASTPommeEnumDefault_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeEnumDefault : public PommeNode {
public: 
           ASTPommeEnumDefault(int id);
           ASTPommeEnumDefault(PommeLexer *parser, int id);
  virtual ~ASTPommeEnumDefault();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
