/* Generated By:JJTree: Do not edit this line. ASTPommeDecls.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDecls_H_
#define ASTPommeDecls_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDecls : public PommeNode {
public: 
           ASTPommeDecls(int id);
           ASTPommeDecls(PommeLexer *parser, int id);
  virtual ~ASTPommeDecls();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
/* JavaCC - OriginalChecksum=3a95cbe9f961f836e0b92d8cdd4199f7 (do not edit this line) */
