/* Generated By:JJTree: Do not edit this line. ASTPommeAccessTab.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeAccessTab.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeAccessTab::ASTPommeAccessTab(int id) : PommeNode(id) {
  }
  ASTPommeAccessTab::ASTPommeAccessTab(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeAccessTab::~ASTPommeAccessTab() {
  }

  /** Accept the visitor. **/
  void  ASTPommeAccessTab::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
