/* Generated By:JJTree: Do not edit this line. ASTpommeModdedEnum.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeModdedEnum_H_
#define ASTpommeModdedEnum_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeModdedEnum : public PommeNode {
public: 
           ASTpommeModdedEnum(int id);
           ASTpommeModdedEnum(PommeLexer *parser, int id);
  virtual ~ASTpommeModdedEnum();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
