/* Generated By:JJTree: Do not edit this line. ASTpommeGlobalFunction.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeGlobalFunction_H_
#define ASTpommeGlobalFunction_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeGlobalFunction : public PommeNode {
public: 
           ASTpommeGlobalFunction(int id);
           ASTpommeGlobalFunction(PommeLexer *parser, int id);
  virtual ~ASTpommeGlobalFunction();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
