/* Generated By:JJTree: Do not edit this line. ASTPommeMultEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeMultEq_H_
#define ASTPommeMultEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeMultEq : public PommeNode {
public: 
           ASTPommeMultEq(int id);
           ASTPommeMultEq(PommeLexer *parser, int id);
  virtual ~ASTPommeMultEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
