/* Generated By:JJTree: Do not edit this line. ASTPommeSwinil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeSwinil_H_
#define ASTPommeSwinil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeSwinil : public PommeNode {
public: 
           ASTPommeSwinil(int id);
           ASTPommeSwinil(PommeLexer *parser, int id);
  virtual ~ASTPommeSwinil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
