/* Generated By:JJTree: Do not edit this line. ASTpommeLET.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeLET.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeLET::ASTpommeLET(int id) : PommeNode(id) {
  }
  ASTpommeLET::ASTpommeLET(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeLET::~ASTpommeLET() {
  }

  /** Accept the visitor. **/
  void  ASTpommeLET::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
