/* Generated By:JJTree: Do not edit this line. ASTpommeEQ.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeEQ.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeEQ::ASTpommeEQ(int id) : PommeNode(id) {
  }
  ASTpommeEQ::ASTpommeEQ(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeEQ::~ASTpommeEQ() {
  }

  /** Accept the visitor. **/
  void  ASTpommeEQ::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
/* JavaCC - OriginalChecksum=d6fbefa605ad7042fa2146d9970fbb97 (do not edit this line) */
