/* Generated By:JJTree: Do not edit this line. ASTPommeConstructor.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeConstructor_H_
#define ASTPommeConstructor_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeConstructor : public PommeNode {
public: 
           ASTPommeConstructor(int id);
           ASTPommeConstructor(PommeLexer *parser, int id);
  virtual ~ASTPommeConstructor();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
