/* Generated By:JJTree: Do not edit this line. ASTpommeReturn.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeReturn_H_
#define ASTpommeReturn_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeReturn : public PommeNode {
public: 
           ASTpommeReturn(int id);
           ASTpommeReturn(PommeLexer *parser, int id);
  virtual ~ASTpommeReturn();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
