/* Generated By:JJTree: Do not edit this line. ASTpommeAnd.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeAnd.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeAnd::ASTpommeAnd(int id) : PommeNode(id) {
  }
  ASTpommeAnd::ASTpommeAnd(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeAnd::~ASTpommeAnd() {
  }

  /** Accept the visitor. **/
  void  ASTpommeAnd::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
