/* Generated By:JJTree: Do not edit this line. ASTPommeSwitch.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeSwitch_H_
#define ASTPommeSwitch_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeSwitch : public PommeNode {
public: 
           ASTPommeSwitch(int id);
           ASTPommeSwitch(PommeLexer *parser, int id);
  virtual ~ASTPommeSwitch();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
