/* Generated By:JJTree: Do not edit this line. ASTpommeEnum.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeEnum.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeEnum::ASTpommeEnum(int id) : PommeNode(id) {
  }
  ASTpommeEnum::ASTpommeEnum(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeEnum::~ASTpommeEnum() {
  }

  /** Accept the visitor. **/
  void  ASTpommeEnum::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
