/* Generated By:JJTree: Do not edit this line. ASTPommeMethodeNative.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeMethodeNative_H_
#define ASTPommeMethodeNative_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeMethodeNative : public PommeNode {
public: 
           ASTPommeMethodeNative(int id);
           ASTPommeMethodeNative(PommeLexer *parser, int id);
  virtual ~ASTPommeMethodeNative();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
