/* Generated By:JJTree: Do not edit this line. ASTpommeModulo.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeModulo_H_
#define ASTpommeModulo_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeModulo : public PommeNode {
public: 
           ASTpommeModulo(int id);
           ASTpommeModulo(PommeLexer *parser, int id);
  virtual ~ASTpommeModulo();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
