/* Generated By:JJTree: Do not edit this line. ASTPommeShiftLEq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeShiftLEq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeShiftLEq::ASTPommeShiftLEq(int id) : PommeNode(id) {
  }
  ASTPommeShiftLEq::ASTPommeShiftLEq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeShiftLEq::~ASTPommeShiftLEq() {
  }

  /** Accept the visitor. **/
  void  ASTPommeShiftLEq::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
