/* Generated By:JJTree: Do not edit this line. ASTPommeVariable.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeVariable_H_
#define ASTPommeVariable_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeVariable : public PommeNode {
public: 
           ASTPommeVariable(int id);
           ASTPommeVariable(PommeLexer *parser, int id);
  virtual ~ASTPommeVariable();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool isStatic = false;
};

}

#endif
