/* Generated By:JJTree: Do not edit this line. ASTpommeConstant.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeConstant.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeConstant::ASTpommeConstant(int id) : PommeNode(id) {
  }
  ASTpommeConstant::ASTpommeConstant(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeConstant::~ASTpommeConstant() {
  }

  /** Accept the visitor. **/
  void  ASTpommeConstant::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
