/* Generated By:JJTree: Do not edit this line. ASTpommeIf.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeIf_H_
#define ASTpommeIf_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeIf : public PommeNode {
public: 
           ASTpommeIf(int id);
           ASTpommeIf(PommeLexer *parser, int id);
  virtual ~ASTpommeIf();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  bool convert = false;
  uint16_t index;
  bool native;

  bool testNull = false;
};

}

#endif
