/* Generated By:JJTree: Do not edit this line. ASTpommeLT.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeLT.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeLT::ASTpommeLT(int id) : PommeNode(id) {
  }
  ASTpommeLT::ASTpommeLT(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeLT::~ASTpommeLT() {
  }

  /** Accept the visitor. **/
  void  ASTpommeLT::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
