/* Generated By:JJTree: Do not edit this line. ASTpommeUnary.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeUnary_H_
#define ASTpommeUnary_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeUnary : public PommeNode {
public: 
           ASTpommeUnary(int id);
           ASTpommeUnary(PommeLexer *parser, int id);
  virtual ~ASTpommeUnary();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
