/* Generated By:JJTree: Do not edit this line. ASTPommeMinus.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeMinus.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeMinus::ASTPommeMinus(int id) : PommeNode(id) {
  }
  ASTPommeMinus::ASTPommeMinus(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeMinus::~ASTPommeMinus() {
  }

  /** Accept the visitor. **/
  void  ASTPommeMinus::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
