/* Generated By:JJTree: Do not edit this line. ASTpommeNot.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTpommeNot_H_
#define ASTpommeNot_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTpommeNot : public PommeNode {
public: 
           ASTpommeNot(int id);
           ASTpommeNot(PommeLexer *parser, int id);
  virtual ~ASTpommeNot();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
