/* Generated By:JJTree: Do not edit this line. ASTPommeEnumAssign.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTPommeEnumAssign.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTPommeEnumAssign::ASTPommeEnumAssign(int id) : PommeNode(id) {
  }
  ASTPommeEnumAssign::ASTPommeEnumAssign(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTPommeEnumAssign::~ASTPommeEnumAssign() {
  }

  /** Accept the visitor. **/
  void  ASTPommeEnumAssign::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
