/* Generated By:JJTree: Do not edit this line. ASTpommeCases.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTpommeCases.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTpommeCases::ASTpommeCases(int id) : PommeNode(id) {
  }
  ASTpommeCases::ASTpommeCases(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTpommeCases::~ASTpommeCases() {
  }

  /** Accept the visitor. **/
  void  ASTpommeCases::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
