/* Generated By:JJTree: Do not edit this line. ASTshiftleq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTshiftleq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTshiftleq::ASTshiftleq(int id) : PommeNode(id) {
  }
  ASTshiftleq::ASTshiftleq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTshiftleq::~ASTshiftleq() {
  }

  /** Accept the visitor. **/
  void  ASTshiftleq::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
