/* Generated By:JJTree: Do not edit this line. ASTshiftleq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTshiftleq_H_
#define ASTshiftleq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTshiftleq : public PommeNode {
public: 
           ASTshiftleq(int id);
           ASTshiftleq(PommeLexer *parser, int id);
  virtual ~ASTshiftleq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
