/* Generated By:JJTree: Do not edit this line. ASTshiftreq.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTshiftreq.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTshiftreq::ASTshiftreq(int id) : PommeNode(id) {
  }
  ASTshiftreq::ASTshiftreq(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTshiftreq::~ASTshiftreq() {
  }

  /** Accept the visitor. **/
  void  ASTshiftreq::jjtAccept(PommeLexerVisitor *visitor, void * data) const {
    return 
    visitor->visit(this, data);
  }

}
