/* Generated By:JJTree: Do not edit this line. ASTscopes.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTscopes_H_
#define ASTscopes_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTscopes : public PommeNode {
public: 
           ASTscopes(int id);
           ASTscopes(PommeLexer *parser, int id);
  virtual ~ASTscopes();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
