/* Generated By:JJTree: Do not edit this line. ASTshiftreq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTshiftreq_H_
#define ASTshiftreq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTshiftreq : public PommeNode {
public: 
           ASTshiftreq(int id);
           ASTshiftreq(PommeLexer *parser, int id);
  virtual ~ASTshiftreq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data) const ;
};

}

#endif
