/* Generated By:JJTree: Do not edit this line. ASTsnil.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTsnil.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTsnil::ASTsnil(int id) : PommeNode(id) {
  }
  ASTsnil::ASTsnil(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTsnil::~ASTsnil() {
  }

  /** Accept the visitor. **/
  void  ASTsnil::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
