/* Generated By:JJTree: Do not edit this line. ASTvarDecls.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTvarDecls_H_
#define ASTvarDecls_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTvarDecls : public PommeNode {
public: 
           ASTvarDecls(int id);
           ASTvarDecls(PommeLexer *parser, int id);
  virtual ~ASTvarDecls();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
