/* Generated By:JJTree: Do not edit this line. ASTvarDecls.cc Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#include "ASTvarDecls.h"
#include "PommeLexerVisitor.h"

namespace Pomme {
  
  ASTvarDecls::ASTvarDecls(int id) : PommeNode(id) {
  }
  ASTvarDecls::ASTvarDecls(PommeLexer *parser, int id) : PommeNode(parser, id) {
  }
  ASTvarDecls::~ASTvarDecls() {
  }

  /** Accept the visitor. **/
  void  ASTvarDecls::jjtAccept(PommeLexerVisitor *visitor, void * data) {
    return 
    visitor->visit(this, data);
  }

}
