/* Generated By:JJTree&JavaCC: Do not edit this line. PommeLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGenCPP#start()
 */
#ifndef POMMELEXERCONSTANTS_H
#define POMMELEXERCONSTANTS_H
#include "JavaCC.h"

namespace Pomme {
  /** End of File. */
const  int _EOF = 0;
  /** RegularExpression Id. */
const  int ASSIGNEMENT = 7;
  /** RegularExpression Id. */
const  int ADD = 8;
  /** RegularExpression Id. */
const  int ADDEQ = 9;
  /** RegularExpression Id. */
const  int MINUS = 10;
  /** RegularExpression Id. */
const  int MINUSEQ = 11;
  /** RegularExpression Id. */
const  int MULT = 12;
  /** RegularExpression Id. */
const  int MULTEQ = 13;
  /** RegularExpression Id. */
const  int DIV = 14;
  /** RegularExpression Id. */
const  int DIVEQ = 15;
  /** RegularExpression Id. */
const  int OREQ = 16;
  /** RegularExpression Id. */
const  int ANDEQ = 17;
  /** RegularExpression Id. */
const  int SHIFTL = 18;
  /** RegularExpression Id. */
const  int SHIFTLEQ = 19;
  /** RegularExpression Id. */
const  int SHIFTR = 20;
  /** RegularExpression Id. */
const  int SHIFTREQ = 21;
  /** RegularExpression Id. */
const  int INCR = 22;
  /** RegularExpression Id. */
const  int DECR = 23;
  /** RegularExpression Id. */
const  int MODULO = 24;
  /** RegularExpression Id. */
const  int CLASS = 25;
  /** RegularExpression Id. */
const  int ENUM = 26;
  /** RegularExpression Id. */
const  int TYPEDEF = 27;
  /** RegularExpression Id. */
const  int IF = 28;
  /** RegularExpression Id. */
const  int ELSE = 29;
  /** RegularExpression Id. */
const  int WHILE = 30;
  /** RegularExpression Id. */
const  int PRINT = 31;
  /** RegularExpression Id. */
const  int RETURN = 32;
  /** RegularExpression Id. */
const  int BREAK = 33;
  /** RegularExpression Id. */
const  int SWITCH = 34;
  /** RegularExpression Id. */
const  int CASE = 35;
  /** RegularExpression Id. */
const  int DEFAULTCASE = 36;
  /** RegularExpression Id. */
const  int PARENTL = 37;
  /** RegularExpression Id. */
const  int PARENTR = 38;
  /** RegularExpression Id. */
const  int BRACEL = 39;
  /** RegularExpression Id. */
const  int BRACER = 40;
  /** RegularExpression Id. */
const  int COLON = 41;
  /** RegularExpression Id. */
const  int SEMICOLON = 42;
  /** RegularExpression Id. */
const  int COMMA = 43;
  /** RegularExpression Id. */
const  int POINT = 44;
  /** RegularExpression Id. */
const  int EXCLAMATION = 45;
  /** RegularExpression Id. */
const  int TILDE = 46;
  /** RegularExpression Id. */
const  int EQ = 47;
  /** RegularExpression Id. */
const  int NEQ = 48;
  /** RegularExpression Id. */
const  int GT = 49;
  /** RegularExpression Id. */
const  int GET = 50;
  /** RegularExpression Id. */
const  int LT = 51;
  /** RegularExpression Id. */
const  int LET = 52;
  /** RegularExpression Id. */
const  int OR = 53;
  /** RegularExpression Id. */
const  int AND = 54;
  /** RegularExpression Id. */
const  int VOID = 55;
  /** RegularExpression Id. */
const  int CONST = 56;
  /** RegularExpression Id. */
const  int NATIVE = 57;
  /** RegularExpression Id. */
const  int EXTENDS = 58;
  /** RegularExpression Id. */
const  int MODDED = 59;
  /** RegularExpression Id. */
const  int STATIC = 60;
  /** RegularExpression Id. */
const  int PUBLIC = 61;
  /** RegularExpression Id. */
const  int PRIVATE = 62;
  /** RegularExpression Id. */
const  int PROTECTED = 63;
  /** RegularExpression Id. */
const  int OVERRIDE = 64;
  /** RegularExpression Id. */
const  int TRUE = 65;
  /** RegularExpression Id. */
const  int FALSE = 66;
  /** RegularExpression Id. */
const  int NULLEXP = 67;
  /** RegularExpression Id. */
const  int NEWEXP = 68;
  /** RegularExpression Id. */
const  int INT = 69;
  /** RegularExpression Id. */
const  int IDENTIFIEROPERATOR = 70;
  /** RegularExpression Id. */
const  int IDENTIFIER = 71;
  /** RegularExpression Id. */
const  int STRING = 72;
  /** RegularExpression Id. */
const  int FLOAT = 73;

  /** Lexical state. */
const  int DEFAULT = 0;

  /** Literal token values. */
  static const JJChar tokenImage_arr_0[] = 
{0x3c, 0x45, 0x4f, 0x46, 0x3e, 0};
  static const JJChar tokenImage_arr_1[] = 
{0x22, 0x20, 0x22, 0};
  static const JJChar tokenImage_arr_2[] = 
{0x22, 0xd, 0x22, 0};
  static const JJChar tokenImage_arr_3[] = 
{0x22, 0x9, 0x22, 0};
  static const JJChar tokenImage_arr_4[] = 
{0x22, 0xa, 0x22, 0};
  static const JJChar tokenImage_arr_5[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x35, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_6[] = 
{0x22, 0x3c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x20, 0x6f, 0x66, 0x20, 0x6b, 0x69, 0x6e, 0x64, 0x20, 0x36, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_7[] = 
{0x22, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_8[] = 
{0x22, 0x2b, 0x22, 0};
  static const JJChar tokenImage_arr_9[] = 
{0x22, 0x2b, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_10[] = 
{0x22, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_11[] = 
{0x22, 0x2d, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_12[] = 
{0x22, 0x2a, 0x22, 0};
  static const JJChar tokenImage_arr_13[] = 
{0x22, 0x2a, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_14[] = 
{0x22, 0x2f, 0x22, 0};
  static const JJChar tokenImage_arr_15[] = 
{0x22, 0x2f, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_16[] = 
{0x22, 0x7c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_17[] = 
{0x22, 0x26, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_18[] = 
{0x22, 0x3c, 0x3c, 0x22, 0};
  static const JJChar tokenImage_arr_19[] = 
{0x22, 0x3c, 0x3c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_20[] = 
{0x22, 0x3e, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_21[] = 
{0x22, 0x3e, 0x3e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_22[] = 
{0x22, 0x2b, 0x2b, 0x22, 0};
  static const JJChar tokenImage_arr_23[] = 
{0x22, 0x2d, 0x2d, 0x22, 0};
  static const JJChar tokenImage_arr_24[] = 
{0x22, 0x25, 0x22, 0};
  static const JJChar tokenImage_arr_25[] = 
{0x22, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x22, 0};
  static const JJChar tokenImage_arr_26[] = 
{0x22, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0};
  static const JJChar tokenImage_arr_27[] = 
{0x22, 0x74, 0x79, 0x70, 0x65, 0x64, 0x65, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_28[] = 
{0x22, 0x69, 0x66, 0x22, 0};
  static const JJChar tokenImage_arr_29[] = 
{0x22, 0x65, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_30[] = 
{0x22, 0x77, 0x68, 0x69, 0x6c, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_31[] = 
{0x22, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_32[] = 
{0x22, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x22, 0};
  static const JJChar tokenImage_arr_33[] = 
{0x22, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x22, 0};
  static const JJChar tokenImage_arr_34[] = 
{0x22, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x22, 0};
  static const JJChar tokenImage_arr_35[] = 
{0x22, 0x63, 0x61, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_36[] = 
{0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_37[] = 
{0x22, 0x28, 0x22, 0};
  static const JJChar tokenImage_arr_38[] = 
{0x22, 0x29, 0x22, 0};
  static const JJChar tokenImage_arr_39[] = 
{0x22, 0x7b, 0x22, 0};
  static const JJChar tokenImage_arr_40[] = 
{0x22, 0x7d, 0x22, 0};
  static const JJChar tokenImage_arr_41[] = 
{0x22, 0x3a, 0x22, 0};
  static const JJChar tokenImage_arr_42[] = 
{0x22, 0x3b, 0x22, 0};
  static const JJChar tokenImage_arr_43[] = 
{0x22, 0x2c, 0x22, 0};
  static const JJChar tokenImage_arr_44[] = 
{0x22, 0x2e, 0x22, 0};
  static const JJChar tokenImage_arr_45[] = 
{0x22, 0x21, 0x22, 0};
  static const JJChar tokenImage_arr_46[] = 
{0x22, 0x7e, 0x22, 0};
  static const JJChar tokenImage_arr_47[] = 
{0x22, 0x3d, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_48[] = 
{0x22, 0x21, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_49[] = 
{0x22, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_50[] = 
{0x22, 0x3e, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_51[] = 
{0x22, 0x3c, 0x22, 0};
  static const JJChar tokenImage_arr_52[] = 
{0x22, 0x3c, 0x3d, 0x22, 0};
  static const JJChar tokenImage_arr_53[] = 
{0x22, 0x7c, 0x7c, 0x22, 0};
  static const JJChar tokenImage_arr_54[] = 
{0x22, 0x26, 0x26, 0x22, 0};
  static const JJChar tokenImage_arr_55[] = 
{0x22, 0x76, 0x6f, 0x69, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_56[] = 
{0x22, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x22, 0};
  static const JJChar tokenImage_arr_57[] = 
{0x22, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_58[] = 
{0x22, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x73, 0x22, 0};
  static const JJChar tokenImage_arr_59[] = 
{0x22, 0x6d, 0x6f, 0x64, 0x64, 0x65, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_60[] = 
{0x22, 0x73, 0x74, 0x61, 0x74, 0x69, 0x63, 0x22, 0};
  static const JJChar tokenImage_arr_61[] = 
{0x22, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0};
  static const JJChar tokenImage_arr_62[] = 
{0x22, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_63[] = 
{0x22, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0};
  static const JJChar tokenImage_arr_64[] = 
{0x22, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_65[] = 
{0x22, 0x74, 0x72, 0x75, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_66[] = 
{0x22, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x22, 0};
  static const JJChar tokenImage_arr_67[] = 
{0x22, 0x6e, 0x75, 0x6c, 0x6c, 0x22, 0};
  static const JJChar tokenImage_arr_68[] = 
{0x22, 0x6e, 0x65, 0x77, 0x22, 0};
  static const JJChar tokenImage_arr_69[] = 
{0x22, 0x3c, 0x49, 0x4e, 0x54, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_70[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x4f, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_71[] = 
{0x22, 0x3c, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49, 0x45, 0x52, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_72[] = 
{0x22, 0x3c, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x3e, 0x22, 0};
  static const JJChar tokenImage_arr_73[] = 
{0x22, 0x3c, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x3e, 0x22, 0};
  static const JJChar* const tokenImage[] = {
tokenImage_arr_0, 
tokenImage_arr_1, 
tokenImage_arr_2, 
tokenImage_arr_3, 
tokenImage_arr_4, 
tokenImage_arr_5, 
tokenImage_arr_6, 
tokenImage_arr_7, 
tokenImage_arr_8, 
tokenImage_arr_9, 
tokenImage_arr_10, 
tokenImage_arr_11, 
tokenImage_arr_12, 
tokenImage_arr_13, 
tokenImage_arr_14, 
tokenImage_arr_15, 
tokenImage_arr_16, 
tokenImage_arr_17, 
tokenImage_arr_18, 
tokenImage_arr_19, 
tokenImage_arr_20, 
tokenImage_arr_21, 
tokenImage_arr_22, 
tokenImage_arr_23, 
tokenImage_arr_24, 
tokenImage_arr_25, 
tokenImage_arr_26, 
tokenImage_arr_27, 
tokenImage_arr_28, 
tokenImage_arr_29, 
tokenImage_arr_30, 
tokenImage_arr_31, 
tokenImage_arr_32, 
tokenImage_arr_33, 
tokenImage_arr_34, 
tokenImage_arr_35, 
tokenImage_arr_36, 
tokenImage_arr_37, 
tokenImage_arr_38, 
tokenImage_arr_39, 
tokenImage_arr_40, 
tokenImage_arr_41, 
tokenImage_arr_42, 
tokenImage_arr_43, 
tokenImage_arr_44, 
tokenImage_arr_45, 
tokenImage_arr_46, 
tokenImage_arr_47, 
tokenImage_arr_48, 
tokenImage_arr_49, 
tokenImage_arr_50, 
tokenImage_arr_51, 
tokenImage_arr_52, 
tokenImage_arr_53, 
tokenImage_arr_54, 
tokenImage_arr_55, 
tokenImage_arr_56, 
tokenImage_arr_57, 
tokenImage_arr_58, 
tokenImage_arr_59, 
tokenImage_arr_60, 
tokenImage_arr_61, 
tokenImage_arr_62, 
tokenImage_arr_63, 
tokenImage_arr_64, 
tokenImage_arr_65, 
tokenImage_arr_66, 
tokenImage_arr_67, 
tokenImage_arr_68, 
tokenImage_arr_69, 
tokenImage_arr_70, 
tokenImage_arr_71, 
tokenImage_arr_72, 
tokenImage_arr_73, 
  };

}
#endif
