/* Generated By:JJTree: Do not edit this line. ASTPommeUnary.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeUnary_H_
#define ASTPommeUnary_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeUnary : public PommeNode {
public: 
           ASTPommeUnary(int id);
           ASTPommeUnary(PommeLexer *parser, int id);
  virtual ~ASTPommeUnary();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
