/* Generated By:JJTree: Do not edit this line. ASTPommeTilde.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeTilde_H_
#define ASTPommeTilde_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeTilde : public PommeNode {
public: 
           ASTPommeTilde(int id);
           ASTPommeTilde(PommeLexer *parser, int id);
  virtual ~ASTPommeTilde();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
