/* Generated By:JJTree: Do not edit this line. ASTPommeReturn.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeReturn_H_
#define ASTPommeReturn_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeReturn : public PommeNode {
public: 
           ASTPommeReturn(int id);
           ASTPommeReturn(PommeLexer *parser, int id);
  virtual ~ASTPommeReturn();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
