/* Generated By:JJTree: Do not edit this line. ASTPommeOverride.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeOverride_H_
#define ASTPommeOverride_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeOverride : public PommeNode {
public: 
           ASTPommeOverride(int id);
           ASTPommeOverride(PommeLexer *parser, int id);
  virtual ~ASTPommeOverride();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
