/* Generated By:JJTree: Do not edit this line. ASTPommeEnumAssign.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeEnumAssign_H_
#define ASTPommeEnumAssign_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeEnumAssign : public PommeNode {
public: 
           ASTPommeEnumAssign(int id);
           ASTPommeEnumAssign(PommeLexer *parser, int id);
  virtual ~ASTPommeEnumAssign();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
