/* Generated By:JJTree: Do not edit this line. ASTPommeConstant.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeConstant_H_
#define ASTPommeConstant_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeConstant : public PommeNode {
public: 
           ASTPommeConstant(int id);
           ASTPommeConstant(PommeLexer *parser, int id);
  virtual ~ASTPommeConstant();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
};

}

#endif
