/* Generated By:JJTree: Do not edit this line. ASTPommeSnil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeSnil_H_
#define ASTPommeSnil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeSnil : public PommeNode {
public: 
           ASTPommeSnil(int id);
           ASTPommeSnil(PommeLexer *parser, int id);
  virtual ~ASTPommeSnil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
