/* Generated By:JJTree: Do not edit this line. ASTPommeAdd.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeAdd_H_
#define ASTPommeAdd_H_

#include "PommeNode.h"
#include "Chunk.h"

namespace Pomme {
class PommeLexer;

class ASTPommeAdd : public PommeNode {
public: 
           ASTPommeAdd(int id);
           ASTPommeAdd(PommeLexer *parser, int id);
  virtual ~ASTPommeAdd();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
  bool primitive = false;
  OpCode opCode;
};

}

#endif
