/* Generated By:JJTree: Do not edit this line. ASTPommeModdedClass.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeModdedClass_H_
#define ASTPommeModdedClass_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeModdedClass : public PommeNode {
public: 
           ASTPommeModdedClass(int id);
           ASTPommeModdedClass(PommeLexer *parser, int id);
  virtual ~ASTPommeModdedClass();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  std::string defaultClassName;
  std::string parentName;

  uint64_t nmbMethods = 0;
  uint64_t nmbNativeMethods = 0;
  uint64_t nmbStaticFields = 0;
  uint64_t nmbFields = 0;
  bool generateDefaultConstructor = false;
  uint16_t defaultConstructorIndex = 0u;
  std::string constructorIdent = "";
  uint16_t defaultSuperConstructorIndex = 0u;
};

}

#endif
