/* Generated By:JJTree: Do not edit this line. ASTPommeScinil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeScinil_H_
#define ASTPommeScinil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeScinil : public PommeNode {
public: 
           ASTPommeScinil(int id);
           ASTPommeScinil(PommeLexer *parser, int id);
  virtual ~ASTPommeScinil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
