/* Generated By:JJTree: Do not edit this line. ASTPommeAndEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeAndEq_H_
#define ASTPommeAndEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeAndEq : public PommeNode {
public: 
           ASTPommeAndEq(int id);
           ASTPommeAndEq(PommeLexer *parser, int id);
  virtual ~ASTPommeAndEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
