/* Generated By:JJTree: Do not edit this line. ASTPommePrint.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommePrint_H_
#define ASTPommePrint_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommePrint : public PommeNode {
public: 
           ASTPommePrint(int id);
           ASTPommePrint(PommeLexer *parser, int id);
  virtual ~ASTPommePrint();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
