/* Generated By:JJTree: Do not edit this line. ASTPommeGlobalFunctionNative.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeGlobalFunctionNative_H_
#define ASTPommeGlobalFunctionNative_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeGlobalFunctionNative : public PommeNode {
public: 
           ASTPommeGlobalFunctionNative(int id);
           ASTPommeGlobalFunctionNative(PommeLexer *parser, int id);
  virtual ~ASTPommeGlobalFunctionNative();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
