/* Generated By:JJTree: Do not edit this line. ASTPommeIdentOp.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeIdentOp_H_
#define ASTPommeIdentOp_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeIdentOp : public PommeNode {
public: 
           ASTPommeIdentOp(int id);
           ASTPommeIdentOp(PommeLexer *parser, int id);
  virtual ~ASTPommeIdentOp();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  std::string m_Identifier;
  std::string m_MethodIdentifier;
  uint16_t m_IndexAttribute = 0;
};

}

#endif
