/* Generated By:JJTree: Do not edit this line. ASTPommeShiftL.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeShiftL_H_
#define ASTPommeShiftL_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeShiftL : public PommeNode {
public: 
           ASTPommeShiftL(int id);
           ASTPommeShiftL(PommeLexer *parser, int id);
  virtual ~ASTPommeShiftL();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
