/* Generated By:JJTree: Do not edit this line. ASTPommeEnnil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeEnnil_H_
#define ASTPommeEnnil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeEnnil : public PommeNode {
public: 
           ASTPommeEnnil(int id);
           ASTPommeEnnil(PommeLexer *parser, int id);
  virtual ~ASTPommeEnnil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
