/* Generated By:JJTree: Do not edit this line. ASTPommeVarDecls.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeVarDecls_H_
#define ASTPommeVarDecls_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeVarDecls : public PommeNode {
public: 
           ASTPommeVarDecls(int id);
           ASTPommeVarDecls(PommeLexer *parser, int id);
  virtual ~ASTPommeVarDecls();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
