/* Generated By:JJTree: Do not edit this line. ASTPommeTrue.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeTrue_H_
#define ASTPommeTrue_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeTrue : public PommeNode {
public: 
           ASTPommeTrue(int id);
           ASTPommeTrue(PommeLexer *parser, int id);
  virtual ~ASTPommeTrue();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
