/* Generated By:JJTree: Do not edit this line. ASTPommeDivEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDivEq_H_
#define ASTPommeDivEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDivEq : public PommeNode {
public: 
           ASTPommeDivEq(int id);
           ASTPommeDivEq(PommeLexer *parser, int id);
  virtual ~ASTPommeDivEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
