/* Generated By:JJTree: Do not edit this line. ASTPommeFloat.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeFloat_H_
#define ASTPommeFloat_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeFloat : public PommeNode {
public: 
           ASTPommeFloat(int id);
           ASTPommeFloat(PommeLexer *parser, int id);
  virtual ~ASTPommeFloat();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  double m_Value;
};

}

#endif
