/* Generated By:JJTree: Do not edit this line. ASTPommeString.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeString_H_
#define ASTPommeString_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeString : public PommeNode {
public: 
           ASTPommeString(int id);
           ASTPommeString(PommeLexer *parser, int id);
  virtual ~ASTPommeString();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  std::string m_Value;
};

}

#endif
