/* Generated By:JJTree: Do not edit this line. ASTPommeVinil.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeVinil_H_
#define ASTPommeVinil_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeVinil : public PommeNode {
public: 
           ASTPommeVinil(int id);
           ASTPommeVinil(PommeLexer *parser, int id);
  virtual ~ASTPommeVinil();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
