/* Generated By:JJTree: Do not edit this line. ASTPommeShiftLEq.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeShiftLEq_H_
#define ASTPommeShiftLEq_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeShiftLEq : public PommeNode {
public: 
           ASTPommeShiftLEq(int id);
           ASTPommeShiftLEq(PommeLexer *parser, int id);
  virtual ~ASTPommeShiftLEq();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index;
  bool native;
};

}

#endif
