/* Generated By:JJTree: Do not edit this line. ASTPommeNew.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeNew_H_
#define ASTPommeNew_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeNew : public PommeNode {
public: 
           ASTPommeNew(int id);
           ASTPommeNew(PommeLexer *parser, int id);
  virtual ~ASTPommeNew();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);

  uint16_t index = 0;
  bool foundConstructor = false;
};

}

#endif
