/* Generated By:JJTree: Do not edit this line. ASTPommeScopes.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeScopes_H_
#define ASTPommeScopes_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeScopes : public PommeNode {
public: 
           ASTPommeScopes(int id);
           ASTPommeScopes(PommeLexer *parser, int id);
  virtual ~ASTPommeScopes();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
