/* Generated By:JJTree: Do not edit this line. ASTPommeTypeDef.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeTypeDef_H_
#define ASTPommeTypeDef_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeTypeDef : public PommeNode {
public: 
           ASTPommeTypeDef(int id);
           ASTPommeTypeDef(PommeLexer *parser, int id);
  virtual ~ASTPommeTypeDef();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
