/* Generated By:JJTree: Do not edit this line. ASTPommeDeclEnums.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeDeclEnums_H_
#define ASTPommeDeclEnums_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeDeclEnums : public PommeNode {
public: 
           ASTPommeDeclEnums(int id);
           ASTPommeDeclEnums(PommeLexer *parser, int id);
  virtual ~ASTPommeDeclEnums();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
