/* Generated By:JJTree: Do not edit this line. ASTPommeVoidType.h Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
#ifndef ASTPommeVoidType_H_
#define ASTPommeVoidType_H_

#include "PommeNode.h"

namespace Pomme {
class PommeLexer;

class ASTPommeVoidType : public PommeNode {
public: 
           ASTPommeVoidType(int id);
           ASTPommeVoidType(PommeLexer *parser, int id);
  virtual ~ASTPommeVoidType();

  /** Accept the visitor. **/
  virtual void  jjtAccept(PommeLexerVisitor *visitor, void * data);
};

}

#endif
